### PR TITLE
format: use prettier

### PR DESCRIPTION
**Pull request by pancaek**
The diff is giant, but it will make future PRs easier to compare if everyone uses prettier

### CODE REVIEW

**Review by Nikoraito — CHANGES_REQUESTED** [review]
Yay! Just a couple things. The project is already formatted using prettier but your settings are different from mine:
1. At min, apply the 'use single quotes' and 'use tabs' options and re-PR, I think that's all that I changed in prettier.
2. If you're able to put the prettier configuration IN the repo so that developers' IDEs (or at least VSCode) can read it, that would be excellent because that would mean it's irrelevant what their workstation defaults are and force consistent formatting across the project.
3. If possible, look into git hooks and see if you can add a pre-commit git hook that automatically runs prettier on all files when you commit; this will ensure that nobody makes a PR that alters formatting bc the previous person forgot to run it.

If you do just 1 I'll most likely approve! 2 would be great, but 2 and 3 could also break out into separate issues and be handled later.

**Review by Nikoraito — APPROVED** [review]
Awesome!!! sbnu~ (sejen bra navun)

**Comment by pancaek** [comment]
This wasn't done!! Still adding hooks

**Comment by pancaek** [comment]
I can submit a separate PR, I suppose

**Pull request merged**
